### ISSUE TITLE
歌手信息接口是bug吗

### ISSUE THREAD

**Issue by heightzhang** [ecitlm/Kugou-api#1]
浏览器输入http://m.kugou.com/singer/info/3060&json=true  后, 返回的是一个html页面. 楼主,求助~~!

**Comment by ecitlm** [comment]
Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1

这是手机端请求的接口 、将request headers 设置添加 以上信息

**Comment by ecitlm** [comment]
https://api.it919.cn/index.php/api/music/singer_info?singerid=3060  你可以查看我GitHub下的TP5_splider 项目 下的music 类  https://github.com/ecitlm/TP5_Splider/blob/master/apps/api/controller/Music.php

**Comment by heightzhang** [comment]
ok,搞定,谢谢

**Comment by heightzhang** [comment]
楼主,又发现了一个小问题.http://m.kugou.com/plist/index&json=true音乐歌单的列表只有30组数据吗?http://m.kugou.com/plist/index 下面好像挺多的;
